# Generated by Django 4.2.11 on 2025-11-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amg_payement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='msisdn',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ref_trans',
        ),
        migrations.AddField(
            model_name='payment',
            name='clientid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ipaddr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='policy_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_return',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
